// Country states/provinces data
export interface State {
  code: string;
  name: string;
}

export interface Country {
  code: string;
  states: State[];
}

export const states: Country[] = [
  {
    code: 'AF',
    states: [],
  },
  {
    code: 'AL', // Albanian states
    states: [
      { code: 'AL-01', name: 'Berat' },
      { code: 'AL-09', name: 'Dibër' },
      { code: 'AL-02', name: 'Durrës' },
      { code: 'AL-03', name: 'Elbasan' },
      { code: 'AL-04', name: 'Fier' },
      { code: 'AL-05', name: 'Gjirokastër' },
      { code: 'AL-06', name: 'Korçë' },
      { code: 'AL-07', name: 'Kukës' },
      { code: 'AL-08', name: 'Lezhë' },
      { code: 'AL-10', name: 'Shkodër' },
      { code: 'AL-11', name: 'Tirana' },
      { code: 'AL-12', name: 'Vlorë' },
    ],
  },
  {
    code: 'AO', // Angolan states
    states: [
      { code: 'BGO', name: 'Bengo' },
      { code: 'BLU', name: 'Benguela' },
      { code: 'BIE', name: 'Bié' },
      { code: 'CAB', name: 'Cabinda' },
      { code: 'CNN', name: 'Cunene' },
      { code: 'HUA', name: 'Huambo' },
      { code: 'HUI', name: 'Huíla' },
      { code: 'CCU', name: 'Kuando Kubango' },
      { code: 'CNO', name: 'Kwanza-Norte' },
      { code: 'CUS', name: 'Kwanza-Sul' },
      { code: 'LUA', name: 'Luanda' },
      { code: 'LNO', name: 'Lunda-Norte' },
      { code: 'LSU', name: 'Lunda-Sul' },
      { code: 'MAL', name: 'Malanje' },
      { code: 'MOX', name: 'Moxico' },
      { code: 'NAM', name: 'Namibe' },
      { code: 'UIG', name: 'Uíge' },
      { code: 'ZAI', name: 'Zaire' },
    ],
  },
  {
    code: 'AR', // Argentinian provinces
    states: [
      { code: 'C', name: 'Ciudad Autónoma de Buenos Aires' },
      { code: 'B', name: 'Buenos Aires' },
      { code: 'K', name: 'Catamarca' },
      { code: 'H', name: 'Chaco' },
      { code: 'U', name: 'Chubut' },
      { code: 'X', name: 'Córdoba' },
      { code: 'W', name: 'Corrientes' },
      { code: 'E', name: 'Entre Ríos' },
      { code: 'P', name: 'Formosa' },
      { code: 'Y', name: 'Jujuy' },
      { code: 'L', name: 'La Pampa' },
      { code: 'F', name: 'La Rioja' },
      { code: 'M', name: 'Mendoza' },
      { code: 'N', name: 'Misiones' },
      { code: 'Q', name: 'Neuquén' },
      { code: 'R', name: 'Río Negro' },
      { code: 'A', name: 'Salta' },
      { code: 'J', name: 'San Juan' },
      { code: 'D', name: 'San Luis' },
      { code: 'Z', name: 'Santa Cruz' },
      { code: 'S', name: 'Santa Fe' },
      { code: 'G', name: 'Santiago del Estero' },
      { code: 'V', name: 'Tierra del Fuego' },
      { code: 'T', name: 'Tucumán' },
    ],
  },
  {
    code: 'AT',
    states: [],
  },
  {
    code: 'AU', // Australian states
    states: [
      { code: 'ACT', name: 'Australian Capital Territory' },
      { code: 'NSW', name: 'New South Wales' },
      { code: 'NT', name: 'Northern Territory' },
      { code: 'QLD', name: 'Queensland' },
      { code: 'SA', name: 'South Australia' },
      { code: 'TAS', name: 'Tasmania' },
      { code: 'VIC', name: 'Victoria' },
      { code: 'WA', name: 'Western Australia' },
    ],
  },
  {
    code: 'AX',
    states: [],
  },
  {
    code: 'BD', // Bangladeshi districts
    states: [
      { code: 'BD-05', name: 'Bagerhat' },
      { code: 'BD-01', name: 'Bandarban' },
      { code: 'BD-02', name: 'Barguna' },
      { code: 'BD-06', name: 'Barishal' },
      { code: 'BD-07', name: 'Bhola' },
      { code: 'BD-03', name: 'Bogura' },
      { code: 'BD-04', name: 'Brahmanbaria' },
      { code: 'BD-09', name: 'Chandpur' },
      { code: 'BD-10', name: 'Chattogram' },
      { code: 'BD-12', name: 'Chuadanga' },
      { code: 'BD-11', name: "Cox's Bazar" },
      { code: 'BD-08', name: 'Cumilla' },
      { code: 'BD-13', name: 'Dhaka' },
      { code: 'BD-14', name: 'Dinajpur' },
      { code: 'BD-15', name: 'Faridpur ' },
      { code: 'BD-16', name: 'Feni' },
      { code: 'BD-19', name: 'Gaibandha' },
      { code: 'BD-18', name: 'Gazipur' },
      { code: 'BD-17', name: 'Gopalganj' },
      { code: 'BD-20', name: 'Habiganj' },
      { code: 'BD-21', name: 'Jamalpur' },
      { code: 'BD-22', name: 'Jashore' },
      { code: 'BD-25', name: 'Jhalokati' },
      { code: 'BD-23', name: 'Jhenaidah' },
      { code: 'BD-24', name: 'Joypurhat' },
      { code: 'BD-29', name: 'Khagrachhari' },
      { code: 'BD-27', name: 'Khulna' },
      { code: 'BD-26', name: 'Kishoreganj' },
      { code: 'BD-28', name: 'Kurigram' },
      { code: 'BD-30', name: 'Kushtia' },
      { code: 'BD-31', name: 'Lakshmipur' },
      { code: 'BD-32', name: 'Lalmonirhat' },
      { code: 'BD-36', name: 'Madaripur' },
      { code: 'BD-37', name: 'Magura' },
      { code: 'BD-33', name: 'Manikganj ' },
      { code: 'BD-39', name: 'Meherpur' },
      { code: 'BD-38', name: 'Moulvibazar' },
      { code: 'BD-35', name: 'Munshiganj' },
      { code: 'BD-34', name: 'Mymensingh' },
      { code: 'BD-48', name: 'Naogaon' },
      { code: 'BD-43', name: 'Narail' },
      { code: 'BD-40', name: 'Narayanganj' },
      { code: 'BD-42', name: 'Narsingdi' },
      { code: 'BD-44', name: 'Natore' },
      { code: 'BD-45', name: 'Nawabganj' },
      { code: 'BD-41', name: 'Netrakona' },
      { code: 'BD-46', name: 'Nilphamari' },
      { code: 'BD-47', name: 'Noakhali' },
      { code: 'BD-49', name: 'Pabna' },
      { code: 'BD-52', name: 'Panchagarh' },
      { code: 'BD-51', name: 'Patuakhali' },
      { code: 'BD-50', name: 'Pirojpur' },
      { code: 'BD-53', name: 'Rajbari' },
      { code: 'BD-54', name: 'Rajshahi' },
      { code: 'BD-56', name: 'Rangamati' },
      { code: 'BD-55', name: 'Rangpur' },
      { code: 'BD-58', name: 'Satkhira' },
      { code: 'BD-62', name: 'Shariatpur' },
      { code: 'BD-57', name: 'Sherpur' },
      { code: 'BD-59', name: 'Sirajganj' },
      { code: 'BD-61', name: 'Sunamganj' },
      { code: 'BD-60', name: 'Sylhet' },
      { code: 'BD-63', name: 'Tangail' },
      { code: 'BD-64', name: 'Thakurgaon' },
    ],
  },
  {
    code: 'BE',
    states: [],
  },
  {
    code: 'BG', // Bulgarian states
    states: [
      { code: 'BG-01', name: 'Blagoevgrad' },
      { code: 'BG-02', name: 'Burgas' },
      { code: 'BG-08', name: 'Dobrich' },
      { code: 'BG-07', name: 'Gabrovo' },
      { code: 'BG-26', name: 'Haskovo' },
      { code: 'BG-09', name: 'Kardzhali' },
      { code: 'BG-10', name: 'Kyustendil' },
      { code: 'BG-11', name: 'Lovech' },
      { code: 'BG-12', name: 'Montana' },
      { code: 'BG-13', name: 'Pazardzhik' },
      { code: 'BG-14', name: 'Pernik' },
      { code: 'BG-15', name: 'Pleven' },
      { code: 'BG-16', name: 'Plovdiv' },
      { code: 'BG-17', name: 'Razgrad' },
      { code: 'BG-18', name: 'Ruse' },
      { code: 'BG-27', name: 'Shumen' },
      { code: 'BG-19', name: 'Silistra' },
      { code: 'BG-20', name: 'Sliven' },
      { code: 'BG-21', name: 'Smolyan' },
      { code: 'BG-23', name: 'Sofia District' },
      { code: 'BG-22', name: 'Sofia' },
      { code: 'BG-24', name: 'Stara Zagora' },
      { code: 'BG-25', name: 'Targovishte' },
      { code: 'BG-03', name: 'Varna' },
      { code: 'BG-04', name: 'Veliko Tarnovo' },
      { code: 'BG-05', name: 'Vidin' },
      { code: 'BG-06', name: 'Vratsa' },
      { code: 'BG-28', name: 'Yambol' },
    ],
  },
  {
    code: 'BH',
    states: [],
  },
  {
    code: 'BI',
    states: [],
  },
  {
    code: 'BJ', // Beninese states
    states: [
      { code: 'AL', name: 'Alibori' },
      { code: 'AK', name: 'Atakora' },
      { code: 'AQ', name: 'Atlantique' },
      { code: 'BO', name: 'Borgou' },
      { code: 'CO', name: 'Collines' },
      { code: 'KO', name: 'Kouffo' },
      { code: 'DO', name: 'Donga' },
      { code: 'LI', name: 'Littoral' },
      { code: 'MO', name: 'Mono' },
      { code: 'OU', name: 'Ouémé' },
      { code: 'PL', name: 'Plateau' },
      { code: 'ZO', name: 'Zou' },
    ],
  },
  {
    code: 'BO', // Bolivian states
    states: [
      { code: 'BO-B', name: 'Beni' },
      { code: 'BO-H', name: 'Chuquisaca' },
      { code: 'BO-C', name: 'Cochabamba' },
      { code: 'BO-L', name: 'La Paz' },
      { code: 'BO-O', name: 'Oruro' },
      { code: 'BO-N', name: 'Pando' },
      { code: 'BO-P', name: 'Potosí' },
      { code: 'BO-S', name: 'Santa Cruz' },
      { code: 'BO-T', name: 'Tarija' },
    ],
  },
  {
    code: 'BR', // Brazilian states
    states: [
      { code: 'AC', name: 'Acre' },
      { code: 'AL', name: 'Alagoas' },
      { code: 'AP', name: 'Amapá' },
      { code: 'AM', name: 'Amazonas' },
      { code: 'BA', name: 'Bahia' },
      { code: 'CE', name: 'Ceará' },
      { code: 'DF', name: 'Distrito Federal' },
      { code: 'ES', name: 'Espírito Santo' },
      { code: 'GO', name: 'Goiás' },
      { code: 'MA', name: 'Maranhão' },
      { code: 'MT', name: 'Mato Grosso' },
      { code: 'MS', name: 'Mato Grosso do Sul' },
      { code: 'MG', name: 'Minas Gerais' },
      { code: 'PA', name: 'Pará' },
      { code: 'PB', name: 'Paraíba' },
      { code: 'PR', name: 'Paraná' },
      { code: 'PE', name: 'Pernambuco' },
      { code: 'PI', name: 'Piauí' },
      { code: 'RJ', name: 'Rio de Janeiro' },
      { code: 'RN', name: 'Rio Grande do Norte' },
      { code: 'RS', name: 'Rio Grande do Sul' },
      { code: 'RO', name: 'Rondônia' },
      { code: 'RR', name: 'Roraima' },
      { code: 'SC', name: 'Santa Catarina' },
      { code: 'SP', name: 'São Paulo' },
      { code: 'SE', name: 'Sergipe' },
      { code: 'TO', name: 'Tocantins' },
    ],
  },
  {
    code: 'CA', // Canadian states
    states: [
      { code: 'AB', name: 'Alberta' },
      { code: 'BC', name: 'British Columbia' },
      { code: 'MB', name: 'Manitoba' },
      { code: 'NB', name: 'New Brunswick' },
      { code: 'NL', name: 'Newfoundland and Labrador' },
      { code: 'NT', name: 'Northwest Territories' },
      { code: 'NS', name: 'Nova Scotia' },
      { code: 'NU', name: 'Nunavut' },
      { code: 'ON', name: 'Ontario' },
      { code: 'PE', name: 'Prince Edward Island' },
      { code: 'QC', name: 'Quebec' },
      { code: 'SK', name: 'Saskatchewan' },
      { code: 'YT', name: 'Yukon Territory' },
    ],
  },
  {
    code: 'CH', // Swiss cantons
    states: [
      { code: 'AG', name: 'Aargau' },
      { code: 'AR', name: 'Appenzell Ausserrhoden' },
      { code: 'AI', name: 'Appenzell Innerrhoden' },
      { code: 'BL', name: 'Basel-Landschaft' },
      { code: 'BS', name: 'Basel-Stadt' },
      { code: 'BE', name: 'Bern' },
      { code: 'FR', name: 'Fribourg' },
      { code: 'GE', name: 'Geneva' },
      { code: 'GL', name: 'Glarus' },
      { code: 'GR', name: 'Graubünden' },
      { code: 'JU', name: 'Jura' },
      { code: 'LU', name: 'Luzern' },
      { code: 'NE', name: 'Neuchâtel' },
      { code: 'NW', name: 'Nidwalden' },
      { code: 'OW', name: 'Obwalden' },
      { code: 'SH', name: 'Schaffhausen' },
      { code: 'SZ', name: 'Schwyz' },
      { code: 'SO', name: 'Solothurn' },
      { code: 'SG', name: 'St. Gallen' },
      { code: 'TG', name: 'Thurgau' },
      { code: 'TI', name: 'Ticino' },
      { code: 'UR', name: 'Uri' },
      { code: 'VS', name: 'Valais' },
      { code: 'VD', name: 'Vaud' },
      { code: 'ZG', name: 'Zug' },
      { code: 'ZH', name: 'Zürich' },
    ],
  },
  {
    code: 'CL', // Chilean states
    states: [
      { code: 'CL-AI', name: 'Aisén del General Carlos Ibañez del Campo' },
      { code: 'CL-AN', name: 'Antofagasta' },
      { code: 'CL-AP', name: 'Arica y Parinacota' },
      { code: 'CL-AR', name: 'La Araucanía' },
      { code: 'CL-AT', name: 'Atacama' },
      { code: 'CL-BI', name: 'Biobío' },
      { code: 'CL-CO', name: 'Coquimbo' },
      { code: 'CL-LI', name: "Libertador General Bernardo O'Higgins" },
      { code: 'CL-LL', name: 'Los Lagos' },
      { code: 'CL-LR', name: 'Los Ríos' },
      { code: 'CL-MA', name: 'Magallanes' },
      { code: 'CL-ML', name: 'Maule' },
      { code: 'CL-NB', name: 'Ñuble' },
      { code: 'CL-RM', name: 'Región Metropolitana de Santiago' },
      { code: 'CL-TA', name: 'Tarapacá' },
      { code: 'CL-VS', name: 'Valparaíso' },
    ],
  },
  {
    code: 'CN', // Chinese states
    states: [
      { code: 'CN1', name: 'Yunnan / 云南' },
      { code: 'CN2', name: 'Beijing / 北京' },
      { code: 'CN3', name: 'Tianjin / 天津' },
      { code: 'CN4', name: 'Hebei / 河北' },
      { code: 'CN5', name: 'Shanxi / 山西' },
      { code: 'CN6', name: 'Inner Mongolia / 內蒙古' },
      { code: 'CN7', name: 'Liaoning / 辽宁' },
      { code: 'CN8', name: 'Jilin / 吉林' },
      { code: 'CN9', name: 'Heilongjiang / 黑龙江' },
      { code: 'CN10', name: 'Shanghai / 上海' },
      { code: 'CN11', name: 'Jiangsu / 江苏' },
      { code: 'CN12', name: 'Zhejiang / 浙江' },
      { code: 'CN13', name: 'Anhui / 安徽' },
      { code: 'CN14', name: 'Fujian / 福建' },
      { code: 'CN15', name: 'Jiangxi / 江西' },
      { code: 'CN16', name: 'Shandong / 山东' },
      { code: 'CN17', name: 'Henan / 河南' },
      { code: 'CN18', name: 'Hubei / 湖北' },
      { code: 'CN19', name: 'Hunan / 湖南' },
      { code: 'CN20', name: 'Guangdong / 广东' },
      { code: 'CN21', name: 'Guangxi Zhuang / 广西壮族' },
      { code: 'CN22', name: 'Hainan / 海南' },
      { code: 'CN23', name: 'Chongqing / 重庆' },
      { code: 'CN24', name: 'Sichuan / 四川' },
      { code: 'CN25', name: 'Guizhou / 贵州' },
      { code: 'CN26', name: 'Shaanxi / 陕西' },
      { code: 'CN27', name: 'Gansu / 甘肃' },
      { code: 'CN28', name: 'Qinghai / 青海' },
      { code: 'CN29', name: 'Ningxia Hui / 宁夏' },
      { code: 'CN30', name: 'Macao / 澳门' },
      { code: 'CN31', name: 'Tibet / 西藏' },
      { code: 'CN32', name: 'Xinjiang / 新疆' },
    ],
  },
  {
    code: 'CO', // Colombian states
    states: [
      { code: 'CO-AMA', name: 'Amazonas' },
      { code: 'CO-ANT', name: 'Antioquia' },
      { code: 'CO-ARA', name: 'Arauca' },
      { code: 'CO-ATL', name: 'Atlántico' },
      { code: 'CO-BOL', name: 'Bolívar' },
      { code: 'CO-BOY', name: 'Boyacá' },
      { code: 'CO-CAL', name: 'Caldas' },
      { code: 'CO-CAQ', name: 'Caquetá' },
      { code: 'CO-CAS', name: 'Casanare' },
      { code: 'CO-CAU', name: 'Cauca' },
      { code: 'CO-CES', name: 'Cesar' },
      { code: 'CO-CHO', name: 'Chocó' },
      { code: 'CO-COR', name: 'Córdoba' },
      { code: 'CO-CUN', name: 'Cundinamarca' },
      { code: 'CO-DC', name: 'Capital District' },
      { code: 'CO-GUA', name: 'Guainía' },
      { code: 'CO-GUV', name: 'Guaviare' },
      { code: 'CO-HUI', name: 'Huila' },
      { code: 'CO-LAG', name: 'La Guajira' },
      { code: 'CO-MAG', name: 'Magdalena' },
      { code: 'CO-MET', name: 'Meta' },
      { code: 'CO-NAR', name: 'Nariño' },
      { code: 'CO-NSA', name: 'Norte de Santander' },
      { code: 'CO-PUT', name: 'Putumayo' },
      { code: 'CO-QUI', name: 'Quindío' },
      { code: 'CO-RIS', name: 'Risaralda' },
      { code: 'CO-SAN', name: 'Santander' },
      { code: 'CO-SAP', name: 'San Andrés & Providencia' },
      { code: 'CO-SUC', name: 'Sucre' },
      { code: 'CO-TOL', name: 'Tolima' },
      { code: 'CO-VAC', name: 'Valle del Cauca' },
      { code: 'CO-VAU', name: 'Vaupés' },
      { code: 'CO-VID', name: 'Vichada' },
    ],
  },
  {
    code: 'CR', // Costa Rican states
    states: [
      { code: 'CR-A', name: 'Alajuela' },
      { code: 'CR-C', name: 'Cartago' },
      { code: 'CR-G', name: 'Guanacaste' },
      { code: 'CR-H', name: 'Heredia' },
      { code: 'CR-L', name: 'Limón' },
      { code: 'CR-P', name: 'Puntarenas' },
      { code: 'CR-SJ', name: 'San José' },
    ],
  },
  {
    code: 'CZ',
    states: [],
  },
  {
    code: 'DE', // German states
    states: [
      { code: 'DE-BW', name: 'Baden-Württemberg' },
      { code: 'DE-BY', name: 'Bavaria' },
      { code: 'DE-BE', name: 'Berlin' },
      { code: 'DE-BB', name: 'Brandenburg' },
      { code: 'DE-HB', name: 'Bremen' },
      { code: 'DE-HH', name: 'Hamburg' },
      { code: 'DE-HE', name: 'Hesse' },
      { code: 'DE-MV', name: 'Mecklenburg-Vorpommern' },
      { code: 'DE-NI', name: 'Lower Saxony' },
      { code: 'DE-NW', name: 'North Rhine-Westphalia' },
      { code: 'DE-RP', name: 'Rhineland-Palatinate' },
      { code: 'DE-SL', name: 'Saarland' },
      { code: 'DE-SN', name: 'Saxony' },
      { code: 'DE-ST', name: 'Saxony-Anhalt' },
      { code: 'DE-SH', name: 'Schleswig-Holstein' },
      { code: 'DE-TH', name: 'Thuringia' },
    ],
  },
  {
    code: 'DK',
    states: [],
  },
  {
    code: 'ES', // Spanish states
    states: [
      { code: 'C', name: 'A Coruña' },
      { code: 'VI', name: 'Araba/Álava' },
      { code: 'AB', name: 'Albacete' },
      { code: 'A', name: 'Alicante' },
      { code: 'AL', name: 'Almería' },
      { code: 'O', name: 'Asturias' },
      { code: 'AV', name: 'Ávila' },
      { code: 'BA', name: 'Badajoz' },
      { code: 'PM', name: 'Baleares' },
      { code: 'B', name: 'Barcelona' },
      { code: 'BU', name: 'Burgos' },
      { code: 'CC', name: 'Cáceres' },
      { code: 'CA', name: 'Cádiz' },
      { code: 'S', name: 'Cantabria' },
      { code: 'CS', name: 'Castellón' },
      { code: 'CE', name: 'Ceuta' },
      { code: 'CR', name: 'Ciudad Real' },
      { code: 'CO', name: 'Córdoba' },
      { code: 'CU', name: 'Cuenca' },
      { code: 'GI', name: 'Girona' },
      { code: 'GR', name: 'Granada' },
      { code: 'GU', name: 'Guadalajara' },
      { code: 'SS', name: 'Gipuzkoa' },
      { code: 'H', name: 'Huelva' },
      { code: 'HU', name: 'Huesca' },
      { code: 'J', name: 'Jaén' },
      { code: 'LO', name: 'La Rioja' },
      { code: 'GC', name: 'Las Palmas' },
      { code: 'LE', name: 'León' },
      { code: 'L', name: 'Lleida' },
      { code: 'LU', name: 'Lugo' },
      { code: 'M', name: 'Madrid' },
      { code: 'MA', name: 'Málaga' },
      { code: 'ML', name: 'Melilla' },
      { code: 'MU', name: 'Murcia' },
      { code: 'NA', name: 'Navarra' },
      { code: 'OR', name: 'Ourense' },
      { code: 'P', name: 'Palencia' },
      { code: 'PO', name: 'Pontevedra' },
      { code: 'SA', name: 'Salamanca' },
      { code: 'TF', name: 'Santa Cruz de Tenerife' },
      { code: 'SG', name: 'Segovia' },
      { code: 'SE', name: 'Sevilla' },
      { code: 'SO', name: 'Soria' },
      { code: 'T', name: 'Tarragona' },
      { code: 'TE', name: 'Teruel' },
      { code: 'TO', name: 'Toledo' },
      { code: 'V', name: 'Valencia' },
      { code: 'VA', name: 'Valladolid' },
      { code: 'BI', name: 'Biscay' },
      { code: 'ZA', name: 'Zamora' },
      { code: 'Z', name: 'Zaragoza' },
    ],
  },
  {
    code: 'ET',
    states: [],
  },
  {
    code: 'FI',
    states: [],
  },
  {
    code: 'FR',
    states: [],
  },
  {
    code: 'GB', // United Kingdom
    states: [
      { code: 'ENG', name: 'England' },
      { code: 'SCT', name: 'Scotland' },
      { code: 'WLS', name: 'Wales' },
      { code: 'NIR', name: 'Northern Ireland' },
    ],
  },
  {
    code: 'GF',
    states: [],
  },
  {
    code: 'GH', // Ghanaian regions
    states: [
      { code: 'AF', name: 'Ahafo' },
      { code: 'AH', name: 'Ashanti' },
      { code: 'BA', name: 'Brong-Ahafo' },
      { code: 'BO', name: 'Bono' },
      { code: 'BE', name: 'Bono East' },
      { code: 'CP', name: 'Central' },
      { code: 'EP', name: 'Eastern' },
      { code: 'AA', name: 'Greater Accra' },
      { code: 'NE', name: 'North East' },
      { code: 'NP', name: 'Northern' },
      { code: 'OT', name: 'Oti' },
      { code: 'SV', name: 'Savannah' },
      { code: 'UE', name: 'Upper East' },
      { code: 'UW', name: 'Upper West' },
      { code: 'TV', name: 'Volta' },
      { code: 'WP', name: 'Western' },
      { code: 'WN', name: 'Western North' },
    ],
  },
  {
    code: 'IN', // Indian states
    states: [
      { code: 'AP', name: 'Andhra Pradesh' },
      { code: 'AR', name: 'Arunachal Pradesh' },
      { code: 'AS', name: 'Assam' },
      { code: 'BR', name: 'Bihar' },
      { code: 'CT', name: 'Chhattisgarh' },
      { code: 'GA', name: 'Goa' },
      { code: 'GJ', name: 'Gujarat' },
      { code: 'HR', name: 'Haryana' },
      { code: 'HP', name: 'Himachal Pradesh' },
      { code: 'JK', name: 'Jammu and Kashmir' },
      { code: 'JH', name: 'Jharkhand' },
      { code: 'KA', name: 'Karnataka' },
      { code: 'KL', name: 'Kerala' },
      { code: 'LA', name: 'Ladakh' },
      { code: 'MP', name: 'Madhya Pradesh' },
      { code: 'MH', name: 'Maharashtra' },
      { code: 'MN', name: 'Manipur' },
      { code: 'ML', name: 'Meghalaya' },
      { code: 'MZ', name: 'Mizoram' },
      { code: 'NL', name: 'Nagaland' },
      { code: 'OD', name: 'Odisha' },
      { code: 'PB', name: 'Punjab' },
      { code: 'RJ', name: 'Rajasthan' },
      { code: 'SK', name: 'Sikkim' },
      { code: 'TN', name: 'Tamil Nadu' },
      { code: 'TS', name: 'Telangana' },
      { code: 'TR', name: 'Tripura' },
      { code: 'UK', name: 'Uttarakhand' },
      { code: 'UP', name: 'Uttar Pradesh' },
      { code: 'WB', name: 'West Bengal' },
      { code: 'AN', name: 'Andaman and Nicobar Islands' },
      { code: 'CH', name: 'Chandigarh' },
      { code: 'DN', name: 'Dadra and Nagar Haveli' },
      { code: 'DD', name: 'Daman and Diu' },
      { code: 'DL', name: 'Delhi' },
      { code: 'LD', name: 'Lakshadweep' },
      { code: 'PY', name: 'Pondicherry (Puducherry)' },
    ],
  },
  {
    code: 'IT', // Italian provinces
    states: [
      { code: 'AG', name: 'Agrigento' },
      { code: 'AL', name: 'Alessandria' },
      { code: 'AN', name: 'Ancona' },
      { code: 'AO', name: 'Aosta' },
      { code: 'AR', name: 'Arezzo' },
      { code: 'AP', name: 'Ascoli Piceno' },
      { code: 'AT', name: 'Asti' },
      { code: 'AV', name: 'Avellino' },
      { code: 'BA', name: 'Bari' },
      { code: 'BT', name: 'Barletta-Andria-Trani' },
      { code: 'BL', name: 'Belluno' },
      { code: 'BN', name: 'Benevento' },
      { code: 'BG', name: 'Bergamo' },
      { code: 'BI', name: 'Biella' },
      { code: 'BO', name: 'Bologna' },
      { code: 'BZ', name: 'Bolzano' },
      { code: 'BS', name: 'Brescia' },
      { code: 'BR', name: 'Brindisi' },
      { code: 'CA', name: 'Cagliari' },
      { code: 'CL', name: 'Caltanissetta' },
      { code: 'CB', name: 'Campobasso' },
      { code: 'CE', name: 'Caserta' },
      { code: 'CT', name: 'Catania' },
      { code: 'CZ', name: 'Catanzaro' },
      { code: 'CH', name: 'Chieti' },
      { code: 'CO', name: 'Como' },
      { code: 'CS', name: 'Cosenza' },
      { code: 'CR', name: 'Cremona' },
      { code: 'KR', name: 'Crotone' },
      { code: 'CN', name: 'Cuneo' },
      { code: 'EN', name: 'Enna' },
      { code: 'FM', name: 'Fermo' },
      { code: 'FE', name: 'Ferrara' },
      { code: 'FI', name: 'Firenze' },
      { code: 'FG', name: 'Foggia' },
      { code: 'FC', name: 'Forlì-Cesena' },
      { code: 'FR', name: 'Frosinone' },
      { code: 'GE', name: 'Genova' },
      { code: 'GO', name: 'Gorizia' },
      { code: 'GR', name: 'Grosseto' },
      { code: 'IM', name: 'Imperia' },
      { code: 'IS', name: 'Isernia' },
      { code: 'SP', name: 'La Spezia' },
      { code: 'AQ', name: "L'Aquila" },
      { code: 'LT', name: 'Latina' },
      { code: 'LE', name: 'Lecce' },
      { code: 'LC', name: 'Lecco' },
      { code: 'LI', name: 'Livorno' },
      { code: 'LO', name: 'Lodi' },
      { code: 'LU', name: 'Lucca' },
      { code: 'MC', name: 'Macerata' },
      { code: 'MN', name: 'Mantova' },
      { code: 'MS', name: 'Massa-Carrara' },
      { code: 'MT', name: 'Matera' },
      { code: 'ME', name: 'Messina' },
      { code: 'MI', name: 'Milano' },
      { code: 'MO', name: 'Modena' },
      { code: 'MB', name: 'Monza e della Brianza' },
      { code: 'NA', name: 'Napoli' },
      { code: 'NO', name: 'Novara' },
      { code: 'NU', name: 'Nuoro' },
      { code: 'OR', name: 'Oristano' },
      { code: 'PD', name: 'Padova' },
      { code: 'PA', name: 'Palermo' },
      { code: 'PR', name: 'Parma' },
      { code: 'PV', name: 'Pavia' },
      { code: 'PG', name: 'Perugia' },
      { code: 'PU', name: 'Pesaro e Urbino' },
      { code: 'PE', name: 'Pescara' },
      { code: 'PC', name: 'Piacenza' },
      { code: 'PI', name: 'Pisa' },
      { code: 'PT', name: 'Pistoia' },
      { code: 'PN', name: 'Pordenone' },
      { code: 'PZ', name: 'Potenza' },
      { code: 'PO', name: 'Prato' },
      { code: 'RG', name: 'Ragusa' },
      { code: 'RA', name: 'Ravenna' },
      { code: 'RC', name: 'Reggio Calabria' },
      { code: 'RE', name: 'Reggio Emilia' },
      { code: 'RI', name: 'Rieti' },
      { code: 'RN', name: 'Rimini' },
      { code: 'RM', name: 'Roma' },
      { code: 'RO', name: 'Rovigo' },
      { code: 'SA', name: 'Salerno' },
      { code: 'SS', name: 'Sassari' },
      { code: 'SV', name: 'Savona' },
      { code: 'SI', name: 'Siena' },
      { code: 'SR', name: 'Siracusa' },
      { code: 'SO', name: 'Sondrio' },
      { code: 'SU', name: 'Sud Sardegna' },
      { code: 'TA', name: 'Taranto' },
      { code: 'TE', name: 'Teramo' },
      { code: 'TR', name: 'Terni' },
      { code: 'TO', name: 'Torino' },
      { code: 'TP', name: 'Trapani' },
      { code: 'TN', name: 'Trento' },
      { code: 'TV', name: 'Treviso' },
      { code: 'TS', name: 'Trieste' },
      { code: 'UD', name: 'Udine' },
      { code: 'VA', name: 'Varese' },
      { code: 'VE', name: 'Venezia' },
      { code: 'VB', name: 'Verbano-Cusio-Ossola' },
      { code: 'VC', name: 'Vercelli' },
      { code: 'VR', name: 'Verona' },
      { code: 'VV', name: 'Vibo Valentia' },
      { code: 'VI', name: 'Vicenza' },
      { code: 'VT', name: 'Viterbo' },
    ],
  },
  {
    code: 'JP', // Japanese prefectures
    states: [
      { code: 'JP01', name: 'Hokkaido' },
      { code: 'JP02', name: 'Aomori' },
      { code: 'JP03', name: 'Iwate' },
      { code: 'JP04', name: 'Miyagi' },
      { code: 'JP05', name: 'Akita' },
      { code: 'JP06', name: 'Yamagata' },
      { code: 'JP07', name: 'Fukushima' },
      { code: 'JP08', name: 'Ibaraki' },
      { code: 'JP09', name: 'Tochigi' },
      { code: 'JP10', name: 'Gunma' },
      { code: 'JP11', name: 'Saitama' },
      { code: 'JP12', name: 'Chiba' },
      { code: 'JP13', name: 'Tokyo' },
      { code: 'JP14', name: 'Kanagawa' },
      { code: 'JP15', name: 'Niigata' },
      { code: 'JP16', name: 'Toyama' },
      { code: 'JP17', name: 'Ishikawa' },
      { code: 'JP18', name: 'Fukui' },
      { code: 'JP19', name: 'Yamanashi' },
      { code: 'JP20', name: 'Nagano' },
      { code: 'JP21', name: 'Gifu' },
      { code: 'JP22', name: 'Shizuoka' },
      { code: 'JP23', name: 'Aichi' },
      { code: 'JP24', name: 'Mie' },
      { code: 'JP25', name: 'Shiga' },
      { code: 'JP26', name: 'Kyoto' },
      { code: 'JP27', name: 'Osaka' },
      { code: 'JP28', name: 'Hyogo' },
      { code: 'JP29', name: 'Nara' },
      { code: 'JP30', name: 'Wakayama' },
      { code: 'JP31', name: 'Tottori' },
      { code: 'JP32', name: 'Shimane' },
      { code: 'JP33', name: 'Okayama' },
      { code: 'JP34', name: 'Hiroshima' },
      { code: 'JP35', name: 'Yamaguchi' },
      { code: 'JP36', name: 'Tokushima' },
      { code: 'JP37', name: 'Kagawa' },
      { code: 'JP38', name: 'Ehime' },
      { code: 'JP39', name: 'Kochi' },
      { code: 'JP40', name: 'Fukuoka' },
      { code: 'JP41', name: 'Saga' },
      { code: 'JP42', name: 'Nagasaki' },
      { code: 'JP43', name: 'Kumamoto' },
      { code: 'JP44', name: 'Oita' },
      { code: 'JP45', name: 'Miyazaki' },
      { code: 'JP46', name: 'Kagoshima' },
      { code: 'JP47', name: 'Okinawa' },
    ],
  },
  {
    code: 'US', // United States
    states: [
      { code: 'AL', name: 'Alabama' },
      { code: 'AK', name: 'Alaska' },
      { code: 'AZ', name: 'Arizona' },
      { code: 'AR', name: 'Arkansas' },
      { code: 'CA', name: 'California' },
      { code: 'CO', name: 'Colorado' },
      { code: 'CT', name: 'Connecticut' },
      { code: 'DE', name: 'Delaware' },
      { code: 'FL', name: 'Florida' },
      { code: 'GA', name: 'Georgia' },
      { code: 'HI', name: 'Hawaii' },
      { code: 'ID', name: 'Idaho' },
      { code: 'IL', name: 'Illinois' },
      { code: 'IN', name: 'Indiana' },
      { code: 'IA', name: 'Iowa' },
      { code: 'KS', name: 'Kansas' },
      { code: 'KY', name: 'Kentucky' },
      { code: 'LA', name: 'Louisiana' },
      { code: 'ME', name: 'Maine' },
      { code: 'MD', name: 'Maryland' },
      { code: 'MA', name: 'Massachusetts' },
      { code: 'MI', name: 'Michigan' },
      { code: 'MN', name: 'Minnesota' },
      { code: 'MS', name: 'Mississippi' },
      { code: 'MO', name: 'Missouri' },
      { code: 'MT', name: 'Montana' },
      { code: 'NE', name: 'Nebraska' },
      { code: 'NV', name: 'Nevada' },
      { code: 'NH', name: 'New Hampshire' },
      { code: 'NJ', name: 'New Jersey' },
      { code: 'NM', name: 'New Mexico' },
      { code: 'NY', name: 'New York' },
      { code: 'NC', name: 'North Carolina' },
      { code: 'ND', name: 'North Dakota' },
      { code: 'OH', name: 'Ohio' },
      { code: 'OK', name: 'Oklahoma' },
      { code: 'OR', name: 'Oregon' },
      { code: 'PA', name: 'Pennsylvania' },
      { code: 'RI', name: 'Rhode Island' },
      { code: 'SC', name: 'South Carolina' },
      { code: 'SD', name: 'South Dakota' },
      { code: 'TN', name: 'Tennessee' },
      { code: 'TX', name: 'Texas' },
      { code: 'UT', name: 'Utah' },
      { code: 'VT', name: 'Vermont' },
      { code: 'VA', name: 'Virginia' },
      { code: 'WA', name: 'Washington' },
      { code: 'WV', name: 'West Virginia' },
      { code: 'WI', name: 'Wisconsin' },
      { code: 'WY', name: 'Wyoming' },
      { code: 'DC', name: 'Washington DC' },
    ],
  },
];

// Helper functions for working with states data
export const getCountryStates = (countryCode: string): State[] => {
  const country = states.find((c) => c.code === countryCode);
  return country?.states || [];
};

export const getStateName = (countryCode: string, stateCode: string): string => {
  const countryStates = getCountryStates(countryCode);
  const state = countryStates.find((s) => s.code === stateCode);
  return state?.name || '';
};

export const getCountryCodes = (): string[] => {
  return states.map((country) => country.code);
};

export const getAllStatesFlat = (): Array<State & { countryCode: string }> => {
  return states.flatMap((country) =>
    country.states.map((state) => ({
      ...state,
      countryCode: country.code,
    }))
  );
};
